### ISSUE TITLE
Fails to run when using pipx

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/ControlManual#14]
This is what happens when attempting to run via pipx:
```
> python3 -m pipx run ControlManual
Traceback (most recent call last):
  File "/home/zero/.local/pipx/.cache/91919a981bf34f4/bin/ControlManual", line 5, in <module>
    from ControlManual.main import main_wrap
ModuleNotFoundError: No module named 'ControlManual.main'
```
Might be an issue with pipx itself considering the actual source code isn't even in the directory.

**Comment by miameows** [comment]
@ZeroIntensity I think moving the code into a new dir broke it; I'll investigate.

**Comment by ZeroIntensity** [comment]
not very important, closing
